import type { Metadata } from 'next'
import '../ui/globals.css'
import { roboto } from '../ui/fonts'
import { CssBaseline, ThemeProvider } from '@mui/material'
import { darkTheme } from '../ui/themes'
import { Navbar } from '@/ui/components/Navbar'

export const metadata: Metadata = {
  title: 'Cookie Master',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <ThemeProvider theme={darkTheme}>
        <CssBaseline />
        <body className={`${roboto.className} antialiased`}>
          <Navbar />
          {children}
        </body>
      </ThemeProvider>
    </html>
  )
}
